#!/usr/bin/env bash
set -e

echo "╔════════════════════════════════════════════════════════════╗"
echo "║         AI Providers Setup - automate-features            ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Function to prompt for input
prompt_input() {
    local prompt="$1"
    local default="$2"
    local result

    if [ -n "$default" ]; then
        read -p "$prompt [$default]: " result
        result="${result:-$default}"
    else
        read -p "$prompt: " result
    fi

    echo "$result"
}

# Function to prompt yes/no
prompt_yes_no() {
    local prompt="$1"
    local response

    read -p "$prompt (y/N): " response
    case "$response" in
        [yY][eE][sS]|[yY])
            return 0
            ;;
        *)
            return 1
            ;;
    esac
}

# Detect shell
detect_shell() {
    if [ -n "$ZSH_VERSION" ]; then
        echo "zsh"
    elif [ -n "$BASH_VERSION" ]; then
        echo "bash"
    else
        echo "unknown"
    fi
}

# Get rc file path
get_rc_file() {
    local shell_type=$(detect_shell)

    if [ "$shell_type" = "zsh" ]; then
        echo "$HOME/.zshrc"
    elif [ "$shell_type" = "bash" ]; then
        if [ -f "$HOME/.bashrc" ]; then
            echo "$HOME/.bashrc"
        else
            echo "$HOME/.bash_profile"
        fi
    else
        echo "$HOME/.profile"
    fi
}

# Create or update .env file
setup_env_file() {
    local env_file="$1"

    echo -e "\n${BLUE}📝 Setting up environment variables in: $env_file${NC}"

    # Backup existing .env if it exists
    if [ -f "$env_file" ]; then
        cp "$env_file" "$env_file.backup.$(date +%Y%m%d_%H%M%S)"
        echo -e "${YELLOW}   Backed up existing .env file${NC}"
    fi

    # Create .env header if file doesn't exist
    if [ ! -f "$env_file" ]; then
        cat > "$env_file" << 'EOF'
# @arranjae/automate-features - AI Provider Configuration
# Generated by setup-providers.sh

EOF
    fi
}

# Add or update env variable
add_env_var() {
    local env_file="$1"
    local var_name="$2"
    local var_value="$3"
    local comment="$4"

    # Remove existing variable if present
    if grep -q "^${var_name}=" "$env_file" 2>/dev/null; then
        # macOS and Linux compatible sed
        if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i '' "/^${var_name}=/d" "$env_file"
        else
            sed -i "/^${var_name}=/d" "$env_file"
        fi
    fi

    # Add variable with comment
    if [ -n "$comment" ]; then
        echo "" >> "$env_file"
        echo "# $comment" >> "$env_file"
    fi
    echo "${var_name}=${var_value}" >> "$env_file"
}

# Setup Claude Code provider
setup_claude() {
    echo -e "\n${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║                  Claude Code Setup                         ║${NC}"
    echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo "Claude Code is Anthropic's official AI assistant."
    echo "You'll need an API key from: https://console.anthropic.com/"
    echo ""

    if prompt_yes_no "Do you want to set up Claude Code?"; then
        local api_key=$(prompt_input "Enter your Anthropic API key (sk-...)")
        local model=$(prompt_input "Choose Claude model (opus/sonnet/haiku)" "sonnet")
        local use_cli=$(prompt_input "Use CLI mode? (true/false)" "false")

        add_env_var "$ENV_FILE" "ANTHROPIC_API_KEY" "$api_key" "Claude Code Configuration"
        add_env_var "$ENV_FILE" "PROMPT_AI_TYPE" "CLAUDE_CODE"
        add_env_var "$ENV_FILE" "CLAUDE_MODEL" "$model"
        add_env_var "$ENV_FILE" "USE_CLI" "$use_cli"

        echo -e "${GREEN}   ✅ Claude Code configured successfully!${NC}"

        # Check if Claude CLI is installed (only if USE_CLI=true)
        if [ "$use_cli" = "true" ]; then
            if command -v claude &> /dev/null; then
                echo -e "${GREEN}   ✅ Claude CLI is installed${NC}"
            else
                echo -e "${YELLOW}   ⚠️  Claude CLI not found${NC}"
                echo -e "${YELLOW}   📖 Install guide: https://docs.anthropic.com/claude/docs/cli${NC}"
            fi
        fi
    else
        echo -e "${YELLOW}   ⏭️  Skipped Claude Code setup${NC}"
    fi
}

# Setup Google Gemini provider
setup_gemini() {
    echo -e "\n${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║                  Google Gemini Setup                       ║${NC}"
    echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo "Google Gemini is Google's AI model with free tier available."
    echo "Get your API key from: https://makersuite.google.com/app/apikey"
    echo ""

    if prompt_yes_no "Do you want to set up Google Gemini?"; then
        local api_key=$(prompt_input "Enter your Google API key (AIza...)")
        local model=$(prompt_input "Choose Gemini model" "gemini-1.5-flash")

        add_env_var "$ENV_FILE" "GOOGLE_API_KEY" "$api_key" "Google Gemini Configuration"
        add_env_var "$ENV_FILE" "PROMPT_AI_TYPE" "GEMINI"
        add_env_var "$ENV_FILE" "GEMINI_MODEL" "$model"
        add_env_var "$ENV_FILE" "USE_CLI" "false" "Gemini only supports API mode"

        echo -e "${GREEN}   ✅ Google Gemini configured successfully!${NC}"
    else
        echo -e "${YELLOW}   ⏭️  Skipped Google Gemini setup${NC}"
    fi
}

# Setup Cursor provider
setup_cursor() {
    echo -e "\n${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║                    Cursor Setup                            ║${NC}"
    echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo "Cursor is an AI-powered code editor."
    echo -e "${YELLOW}Note: Cursor may not have a public API. You might need a private URL.${NC}"
    echo ""

    if prompt_yes_no "Do you want to set up Cursor?"; then
        local api_key=$(prompt_input "Enter your Cursor API token")
        local api_url=$(prompt_input "Enter Cursor API URL (if you have one)" "")

        add_env_var "$ENV_FILE" "CURSOR_API_TOKEN" "$api_key" "Cursor Configuration"
        add_env_var "$ENV_FILE" "PROMPT_AI_TYPE" "CURSOR"
        if [ -n "$api_url" ]; then
            add_env_var "$ENV_FILE" "PROMPT_API_URL" "$api_url"
        fi
        add_env_var "$ENV_FILE" "USE_CLI" "false"

        echo -e "${GREEN}   ✅ Cursor configured successfully!${NC}"
    else
        echo -e "${YELLOW}   ⏭️  Skipped Cursor setup${NC}"
    fi
}

# Setup GitHub integration
setup_github() {
    echo -e "\n${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║               GitHub Integration (Optional)                ║${NC}"
    echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo "GitHub token allows creating issues, branches, and PRs automatically."
    echo "Create a token at: https://github.com/settings/tokens"
    echo "Required scopes: repo, workflow"
    echo ""

    if prompt_yes_no "Do you want to set up GitHub integration?"; then
        local github_token=$(prompt_input "Enter your GitHub Personal Access Token (ghp_...)")
        local repo_owner=$(prompt_input "Enter repository owner (username or org)")
        local repo_name=$(prompt_input "Enter repository name")

        add_env_var "$ENV_FILE" "GITHUB_TOKEN" "$github_token" "GitHub Integration"
        add_env_var "$ENV_FILE" "GITHUB_REPO_OWNER" "$repo_owner"
        add_env_var "$ENV_FILE" "GITHUB_REPO_NAME" "$repo_name"

        echo -e "${GREEN}   ✅ GitHub integration configured successfully!${NC}"

        # Check if gh CLI is installed
        if command -v gh &> /dev/null; then
            echo -e "${GREEN}   ✅ GitHub CLI (gh) is installed${NC}"
        else
            echo -e "${YELLOW}   ⚠️  GitHub CLI (gh) not found${NC}"
            echo -e "${YELLOW}   📖 Install: https://cli.github.com/${NC}"
        fi
    else
        echo -e "${YELLOW}   ⏭️  Skipped GitHub integration${NC}"
    fi
}

# Main setup flow
main() {
    echo ""
    echo "This script will help you configure AI providers for automate-features."
    echo ""

    # Determine .env file location
    ENV_FILE=$(prompt_input "Where should we save the configuration?" "$(pwd)/.env")

    # Create/setup .env file
    setup_env_file "$ENV_FILE"

    # Setup providers
    echo -e "\n${BLUE}📦 Available Providers:${NC}"
    echo "  1. Claude Code (Anthropic) - Recommended"
    echo "  2. Google Gemini - Free tier available"
    echo "  3. Cursor - Requires private access"
    echo ""

    setup_claude
    setup_gemini
    setup_cursor
    setup_github

    # Summary
    echo -e "\n${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║                    Setup Complete! 🎉                       ║${NC}"
    echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "${BLUE}Configuration saved to: $ENV_FILE${NC}"
    echo ""
    echo -e "${BLUE}📖 Next steps:${NC}"
    echo "  1. Source your .env file or restart your shell"
    echo "  2. Test your setup: automate-features --help"
    echo "  3. Generate code: automate-features feature.md"
    echo ""
    echo -e "${BLUE}📚 Documentation:${NC}"
    echo "  • Quick Start: ./docs/QUICK_START.md"
    echo "  • AI Providers: ./docs/AI_PROVIDERS.md"
    echo "  • Claude Setup: ./docs/CLAUDE_CODE_SETUP.md"
    echo ""
}

# Run main function
main
